// Code generated by protoc-gen-go.
// source: phonecontrol.proto
// DO NOT EDIT!

/*
Package phonecontrol is a generated protocol buffer package.

It is generated from these files:
	phonecontrol.proto

It has these top-level messages:
	Request
	Response
	VibrateRequest
*/
package phonecontrol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type VibrateRequest struct {
	VTime []int32 `protobuf:"varint,1,rep,packed,name=v_time,json=vTime" json:"v_time,omitempty"`
}

func (m *VibrateRequest) Reset()                    { *m = VibrateRequest{} }
func (m *VibrateRequest) String() string            { return proto.CompactTextString(m) }
func (*VibrateRequest) ProtoMessage()               {}
func (*VibrateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VibrateRequest) GetVTime() []int32 {
	if m != nil {
		return m.VTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "phonecontrol.Request")
	proto.RegisterType((*Response)(nil), "phonecontrol.Response")
	proto.RegisterType((*VibrateRequest)(nil), "phonecontrol.VibrateRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Service service

type ServiceClient interface {
	GetVolumeState(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	SetSilence(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	SetNormal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Vibrate(ctx context.Context, in *VibrateRequest, opts ...grpc.CallOption) (*Response, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetVolumeState(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/phonecontrol.Service/GetVolumeState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SetSilence(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/phonecontrol.Service/SetSilence", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SetNormal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/phonecontrol.Service/SetNormal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Vibrate(ctx context.Context, in *VibrateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/phonecontrol.Service/Vibrate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	GetVolumeState(context.Context, *Request) (*Response, error)
	SetSilence(context.Context, *Request) (*Response, error)
	SetNormal(context.Context, *Request) (*Response, error)
	Vibrate(context.Context, *VibrateRequest) (*Response, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_GetVolumeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetVolumeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonecontrol.Service/GetVolumeState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetVolumeState(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SetSilence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SetSilence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonecontrol.Service/SetSilence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SetSilence(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SetNormal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SetNormal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonecontrol.Service/SetNormal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SetNormal(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Vibrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VibrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Vibrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonecontrol.Service/Vibrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Vibrate(ctx, req.(*VibrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phonecontrol.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVolumeState",
			Handler:    _Service_GetVolumeState_Handler,
		},
		{
			MethodName: "SetSilence",
			Handler:    _Service_SetSilence_Handler,
		},
		{
			MethodName: "SetNormal",
			Handler:    _Service_SetNormal_Handler,
		},
		{
			MethodName: "Vibrate",
			Handler:    _Service_Vibrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phonecontrol.proto",
}

func init() { proto.RegisterFile("phonecontrol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0xd1, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0x07, 0x70, 0x6a, 0x69, 0x6b, 0x07, 0xe9, 0x61, 0xa0, 0x1f, 0x96, 0xaa, 0x65, 0x11, 0xec,
	0xa9, 0x0b, 0xfa, 0x10, 0xde, 0x3c, 0xec, 0x4a, 0x2f, 0xa2, 0x92, 0x96, 0xa1, 0x46, 0xb2, 0x99,
	0x35, 0x99, 0xee, 0x03, 0x78, 0xf6, 0xe6, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x98, 0x2c, 0xa5, 0x15,
	0x3c, 0xf4, 0x98, 0x21, 0xf3, 0xfb, 0x0f, 0x33, 0x80, 0xe5, 0x0b, 0x5b, 0x5a, 0xb1, 0x15, 0xc7,
	0x66, 0x5e, 0x3a, 0x16, 0xc6, 0x93, 0xdd, 0xda, 0x78, 0xb2, 0x66, 0x5e, 0x1b, 0x4a, 0x55, 0xa9,
	0x53, 0x65, 0x2d, 0x8b, 0x12, 0xcd, 0xd6, 0xc7, 0xbf, 0x49, 0x17, 0x3a, 0x19, 0xbd, 0x6d, 0xc8,
	0x4b, 0x92, 0xc0, 0x71, 0x46, 0xbe, 0x64, 0xeb, 0x09, 0x07, 0xd0, 0x76, 0xe4, 0x37, 0x46, 0x46,
	0x8d, 0x69, 0x63, 0xd6, 0xca, 0xea, 0x57, 0x72, 0x05, 0xbd, 0x85, 0x5e, 0x3a, 0x25, 0x54, 0x77,
	0x61, 0x1f, 0xda, 0xd5, 0xb3, 0xe8, 0x82, 0x46, 0x8d, 0x69, 0x73, 0xd6, 0xca, 0x5a, 0xd5, 0xbd,
	0x2e, 0xe8, 0xfa, 0xa3, 0x09, 0x9d, 0x9c, 0x5c, 0xa5, 0x57, 0x84, 0x04, 0xbd, 0x5b, 0x92, 0x05,
	0x9b, 0x4d, 0x41, 0xb9, 0x28, 0x21, 0xec, 0xcf, 0xf7, 0xc6, 0xae, 0xad, 0xf1, 0xe0, 0x6f, 0x39,
	0x4e, 0x93, 0x5c, 0xbe, 0x7f, 0x7d, 0x7f, 0x1e, 0x9d, 0xe3, 0x24, 0xf5, 0x91, 0x4c, 0xd7, 0x24,
	0x55, 0xf0, 0xfc, 0xaf, 0x37, 0x7f, 0xf5, 0x6c, 0xf1, 0x11, 0x20, 0x27, 0xc9, 0xb5, 0x21, 0xbb,
	0x3a, 0x38, 0x62, 0x1a, 0x22, 0xc6, 0x38, 0xda, 0x46, 0x78, 0x12, 0x1f, 0xad, 0xc8, 0x3f, 0x40,
	0x37, 0x27, 0xb9, 0x63, 0x57, 0x28, 0x73, 0xa8, 0x7e, 0x11, 0xf4, 0x53, 0x1c, 0xee, 0xea, 0x36,
	0x50, 0x11, 0x7f, 0x82, 0x4e, 0xbd, 0x57, 0x9c, 0xec, 0x1b, 0xfb, 0xeb, 0xfe, 0x37, 0xe1, 0x2c,
	0x24, 0x0c, 0xb1, 0xbf, 0x4d, 0xa8, 0x62, 0x63, 0xf0, 0x97, 0xed, 0x70, 0xed, 0x9b, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x3a, 0xd7, 0x60, 0x61, 0x2f, 0x02, 0x00, 0x00,
}
